# stdlib
from datetime import datetime
from typing import List, Optional
from uuid import UUID

# third-party
from pydantic import BaseModel, ConfigDict, Field, field_validator


# ─── Ingestion Models ──────────────────────────────────────────────────────────

class PatientIngest(BaseModel):
    """Request model for ingesting a new patient record."""

    model_config = ConfigDict(str_strip_whitespace=True)

    patient_id: Optional[str] = Field(
        default=None, description="Optional UUID; auto-generated if not provided."
    )
    name: str = Field(..., min_length=1, max_length=200, description="Patient full name.")
    age: int = Field(..., ge=1, le=120, description="Patient age (1–120).")
    gender: str = Field(..., description="Patient gender (e.g. Male, Female, Other).")
    symptoms: List[str] = Field(
        ..., min_length=1, description="List of reported symptoms."
    )
    timestamp: Optional[datetime] = Field(
        default=None, description="Record timestamp; defaults to current UTC time."
    )


class PatientIngestResponse(BaseModel):
    """Response model after successfully ingesting a patient record."""

    patient_id: str = Field(..., description="UUID of the ingested patient record.")
    status: str = Field(..., description="Operation status (e.g. 'created', 'updated').")
    message: str = Field(..., description="Human-readable result message.")


# ─── Prediction Models ─────────────────────────────────────────────────────────

class PredictionResult(BaseModel):
    """Single disease prediction with confidence and risk level."""

    disease: str = Field(..., description="Predicted disease name.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model confidence (0–1).")
    risk_level: str = Field(..., description="Risk assessment: 'low', 'medium', or 'high'.")


class PredictRequest(BaseModel):
    """Request model for disease prediction."""

    model_config = ConfigDict(str_strip_whitespace=True)

    symptoms: List[str] = Field(
        ..., min_length=1, description="List of symptom strings (at least 1 required)."
    )
    patient_id: Optional[str] = Field(
        default=None, description="Optional patient ID to link prediction to a record."
    )

    @field_validator("symptoms")
    @classmethod
    def symptoms_must_not_be_empty_strings(cls, v: List[str]) -> List[str]:
        """Ensure no empty strings are in the symptom list."""
        cleaned = [s.strip() for s in v if s.strip()]
        if not cleaned:
            raise ValueError("At least one non-empty symptom string is required.")
        return cleaned


class PredictResponse(BaseModel):
    """Response model containing disease predictions."""

    predictions: List[PredictionResult] = Field(
        ..., description="Ranked list of disease predictions."
    )
    patient_id: Optional[str] = Field(
        default=None, description="Patient ID if provided in the request."
    )
    disclaimer: str = Field(
        default=(
            "This is not medical advice. These predictions are generated by an AI model "
            "and should not be used as a substitute for professional medical diagnosis. "
            "Please consult a licensed healthcare professional."
        ),
        description="Standard medical disclaimer.",
    )


# ─── Search Models ─────────────────────────────────────────────────────────────

class SearchResult(BaseModel):
    """Single document chunk returned from vector search."""

    content: str = Field(..., description="Text content of the retrieved chunk.")
    source: str = Field(..., description="Source document filename or URL.")
    score: float = Field(..., description="Relevance score (higher = more relevant).")


class SearchRequest(BaseModel):
    """Request model for semantic document search."""

    model_config = ConfigDict(str_strip_whitespace=True)

    query: str = Field(..., min_length=1, description="Natural language search query.")
    top_k: int = Field(default=3, ge=1, le=10, description="Number of results to return.")


class SearchResponse(BaseModel):
    """Response model containing search results."""

    results: List[SearchResult] = Field(..., description="Retrieved document chunks.")
    query: str = Field(..., description="The original search query.")


# ─── Agent Models ──────────────────────────────────────────────────────────────

class AgentRequest(BaseModel):
    """Request model for the multi-agent chat endpoint."""

    model_config = ConfigDict(str_strip_whitespace=True)

    message: str = Field(
        ..., min_length=1, description="User message to the agent system."
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional conversation session ID for maintaining context.",
    )
    intent: Optional[str] = Field(
        default=None,
        description="Optional intent hint: 'triage', 'medical_info', 'analytics', 'general'.",
    )


class AgentResponse(BaseModel):
    """Response model from the agent orchestrator."""

    response: str = Field(..., description="Agent's text response to the user.")
    agent_used: str = Field(
        ..., description="Name of the agent that handled the request."
    )
    session_id: str = Field(
        ..., description="Session ID (auto-generated if not provided in request)."
    )
